### ISSUE TITLE
Roi definition

### ISSUE THREAD

**Issue by dschick** [esrf-bliss/Lima-camera-hamamatsu#2]
Following the definition of lima pytango, the rois are defined as start x - end x and the same for y.

For the hamamatsu the 4 roi parameters are however setting start x and width x and the same for y.

Is that a bug in mapping or did I misunderstood the lima definition?

**Comment by dschick** [comment]
Hi @laurent-claustre 

could you briefly explain how this issue is connected to the lima-version?

Best

Daniel

**Comment by laurent-claustre** [comment]
Hi @dschick ,
you are right, in the documentation there is a mistake (https://lima1.readthedocs.io/en/latest/applications/tango/python/doc/index.html#attributes) for image_roi attribute, the next version of the documentation will correct this.
One should read for image_roi:
```
Region Of Interest on image, [0] = Begin X, [1] = Begin Y, [2] = Width, [3] = Height, default ROI is [0,0,0,0] (no ROI)
```
